{"uuid":"6445a75a-b073-4f12-a9dd-2972f7405be6","historyId":"7d21f962d0d9ab4810f54fb5c947daa8","fullName":"com.maantic.automation.tests.GBTSLATest.SLA","labels":[{"name":"package","value":"com.maantic.automation.tests.GBTSLATest"},{"name":"testClass","value":"com.maantic.automation.tests.GBTSLATest"},{"name":"testMethod","value":"SLA"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"pega-automation-framework"},{"name":"subSuite","value":"com.maantic.automation.tests.GBTSLATest"},{"name":"host","value":"NavneetSingh"},{"name":"thread","value":"11584@NavneetSingh.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"normal"}],"links":[],"name":"Verifying the SLA is working properly.","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [false] but found [true]","trace":"java.lang.AssertionError: expected [false] but found [true]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:819)\r\n\tat org.testng.Assert.assertEquals(Assert.java:829)\r\n\tat com.maantic.automation.tests.GBTSLATest.SLA(GBTSLATest.java:39)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1259)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\r\n\tat org.testng.TestNG.run(TestNG.java:1031)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","description":"Test Case Description: Verify the Decision Table is working properly.","steps":[],"attachments":[{"name":"saveScreenshotOnFailure","source":"3c0ebf11-5e16-41a2-946f-5788649f98a0-attachment","type":"image/png"},{"name":"SLA failed and screenshot taken!","source":"0a710508-5316-40a5-b731-32448398f5e9-attachment","type":"text/plain"}],"parameters":[{"name":"arg0","value":"{Param10=NA, Param11=NA, Expected=NA, Param12=NA, Param9=NA, Param8=NA, Param7=NA, Param6=NA, Param5=NA, Param4=NA, Param3=NA, RuleType=SLA, Param2=NA, Pass/Fail=NA, Param1=NA, RuleSetVersion=PegaCS-Cases:08-06-01, ClassName=PegaCA-Work-Service-GeneralRequest, Actual=NA, RuleName=CAAssignService}"}],"start":1668664895430,"stop":1668664927697}